### ISSUE TITLE
Bypassing recaptcha?

### ISSUE THREAD

**Issue by zun95** [ympo2oo2/Py3SuprBot#3]
As i see you are using selenium,you have any idea to bypassing or fix the google recaptcha problem at checkout page?

**Comment by ympo2oo2** [comment]
Oh, this is the main problem I am facing right now. Unfortunately, I have no idea how to get rid of it. But as I guess, its all about user identification - especially headers and cookies

**Comment by ympo2oo2** [comment]
You have same problem in js?

**Comment by zun95** [comment]
ya,give up at the google recaptcha.But i heard that it can bypass with selenium.
