### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by yousefissa** [ympo2oo2/Py3SuprBot#4]
Any chance we can get in contact with one another? Feel free to shoot me an email. I'd love to talk about some paid work on botting software development if you're interested.

**Comment by ympo2oo2** [comment]
> Any chance we can get in contact with one another? Feel free to shoot me an email. I'd love to talk about some paid work on botting software development if you're interested.
Hello, Yousef!
Will you please provide me with your e-mail address so I can contact you?

**Comment by yousefissa** [comment]
yousef@u.northwestern.edu
