### ISSUE TITLE
Can you help me? 

### ISSUE THREAD

**Issue by ValdemarLarsen** [ympo2oo2/Py3SuprBot#5]
I am on mac Mojav(10.14)

When i try to run the "python3 Py3SuprBot.py" in terminal then i will get this error

I have tried myself figuring it out, but i couldnt the only thing i found is by PyQt4 dosent work on this verison on mac, so is there any way it could get an update to PyQt5

<img width="638" alt="skaermbillede 2018-12-02 kl 19 54 26" src="https://user-images.githubusercontent.com/41428728/49343566-2a37c900-f66c-11e8-9ce1-9334abfe5e46.png">

//Valdemar

**Comment by alshitov** [comment]
> I am on mac Mojav(10.14)
> 
> When i try to run the "python3 Py3SuprBot.py" in terminal then i will get this error
> 
> I have tried myself figuring it out, but i couldnt the only thing i found is by PyQt4 dosent work on this verison on mac, so is there any way it could get an update to PyQt5
> 
> <img alt="skaermbillede 2018-12-02 kl 19 54 26" width="638" src="https://user-images.githubusercontent.com/41428728/49343566-2a37c900-f66c-11e8-9ce1-9334abfe5e46.png">
> 
> //Valdemar

Hi, Valdemar!
Sorry for made you wait for so long. 
What about your problem: PyQt v.4 and v.5 differ from each other is some ways (described here: http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html). Actually there is not one and only pyqt4 to pyqt5 conversion solution. All I can offer you for now is you can try out installing virtual machine with some linux distribution. Thanks.
# Alexander
